import {cashBalances,dividendAmount} from './cash.js';
import {quoteStatus,shouldRefresh} from './quote-status.js';
import {loadFx,fxMode,applyFx} from './fx.js';
import {classifyPurchase} from './book.js';
import {installUpdates} from './updates.js';
import {Notebook,uid,copy,today,day,key,quoteKey,charges,calculate,validate,saveEvent,deleteEvent,performance,mergePositions,usable,signal} from './book.js';
import {resultView,fitMonthlyCharts} from './results.js';
import {reportRange,realizedReport,periodPerformance,priorDate} from './period.js';
import {resolveStock} from './symbols.js';
import {loadCatalog,tiingoQuote,relayOrigin} from './network.js';
import {cashContent,cashOpeningContent,fxContent,assetView,assetDialogContent,targetContent,settingsContent,brokerContent,categoryContent} from './panels.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(v)?new Intl.NumberFormat('zh-TW',{maximumFractionDigits:6}).format(v):'—';
const cash=(v,m='TW')=>Number.isFinite(v)?`${m==='US'||m==='USD'?'US$':'NT$'}${new Intl.NumberFormat('zh-TW',{maximumFractionDigits:m==='US'||m==='USD'?2:0}).format(v)}`:'—';
const unitPrice=(v,m='TW')=>Number.isFinite(v)?`${m==='US'?'US$':'NT$'}${new Intl.NumberFormat('zh-TW',{maximumFractionDigits:6}).format(v)}`:'—';
const pct=v=>Number.isFinite(v)?`${(v*100).toFixed(2)}%`:'—';
const tone=v=>v>0?'gain':v<0?'loss':'';
const kinds={buy:'買入',sell:'賣出',cash:'現金股息',stock:'股票股利',split:'股票分割',fxbuy:'買入美元',fxsell:'賣出美元'};
const buckets=['台股','美股','債券','現金','其他'];
const storageKey=`slow-notebook:1:${new URL('.',location.href).pathname}`,store=new Notebook(localStorage,storageKey);
let state,combined=false,catalog={},page='entry',kind='buy',draft={},stockFilter='',reportMode='month',reportPeriod=today().slice(0,7),reportStock='',reportStart=today().slice(0,7)+'-01',reportEnd=today(),reportPrices={},busy=false,success='',revision=null;
let stockMarket='mixed',pieBasis='value',assetAccount='__all__';
let fieldNumber=0,quoteError='',quoteChecked='',bankQuote=null;
function priceStatus(){const q=quoteStatus(catalog,{online:navigator.onLine,error:quoteError,checkedAt:quoteChecked});return `<aside class="quote-status${q.warning?' signal':''}" role="status"><strong>${busy?'正在檢查行情…':esc(q.message)}</strong><p>${esc(q.detail)}</p><details><summary>更新資訊</summary><p class="meta">${quoteChecked?'本機檢查 '+esc(quoteChecked)+'。':''}非盤中即時；個別停牌／休市請看股票卡片的日期。</p>${quoteError?`<p class="warning">${esc(quoteError)}</p>`:''}<p>開啟、切回、重新連網及停留畫面時會檢查，台灣時間平日 13:45～14:30 每 5 分鐘讀取一次已發布行情，其他時段每小時一次；離線、背景或編輯視窗開啟時暫停。伺服器排程於平日 13:45 抓取官方日收盤，17:17、19:17 再試；排程啟動及發布可能延遲，13:45 不是保證完成時間。舊資料保留原行情日期。Tiingo 自動查詢仍最多每小時一次。</p><p>如果一直不更新：GitHub 須包含 .github/workflows/pages.yml、data、tools，Pages 來源選 GitHub Actions。檢查「更新官方台股行情並發布」是否成功或被停用。</p><button class="text-link" type="button" data-refresh>立即重新讀取行情</button></details></aside>`;}
function updateQuoteStatus(){for(const el of $$('[data-quote-status]'))el.innerHTML=priceStatus();}
const root=$('#workspace'),sheet=$('#sheet');
const ui={field,get problem(){return problem;},esc,cash,pct,tone,pie,account,accountName,defaultBroker,book,classOf,buckets,get state(){return state;},get bankQuote(){return bankQuote;},scoped,connection};
function message(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(message.timer);message.timer=setTimeout(()=>$('#toast').hidden=true,5000);}
function account(){return state.settings.account;}function accountName(id){return state.accounts.find(a=>a.id===id)?.name||'未知帳戶';}function scoped(r){return combined||r.account===account();}function book(){return calculate(state.entries.filter(scoped));}function classOf(p){return state.classes.find(c=>key(c)===key(p));}function categoryName(id){return state.settings.categories.find(c=>c.id===id)?.name||'未分類';}
function commit(fn,expected=null){state=store.change(fn,{expected});}
function options(items,value){return items.map(([id,label])=>`<option value="${esc(id)}"${String(id)===String(value)?' selected':''}>${esc(label)}</option>`).join('');}
function field(label,name,type='text',value='',choices=null,required=false){const fieldId=`f-${name}-${++fieldNumber}`;return `<div class="field"><label for="${fieldId}">${label}</label>${choices?`<select id="${fieldId}" name="${name}">${options(choices,value)}</select>`:`<input id="${fieldId}" name="${name}" type="${type}" value="${esc(value)}"${type==='number'?' min="0" step="any" inputmode="decimal"':''}${required?' required':''}${type==='text'?' maxlength="120"':''}>`}</div>`;}
const problem='<p class="error" data-error role="alert" hidden></p>';
function connection(){try{return JSON.parse(localStorage.getItem(storageKey+':connection')||'{}');}catch{return {};}}
function renderAssets(){const scope=r=>assetAccount==='__all__'||r.account===assetAccount;root.innerHTML=title('','資產')+field('資產帳戶','asset-account','text',assetAccount,[['__all__','全部帳戶'],...state.accounts.map(a=>[a.id,a.name])])+assetView({...ui,scoped:scope,book:()=>calculate(state.entries.filter(scope))});draw();}
function render(){page=['entry','stocks','results','assets'].includes(location.hash.slice(1))?location.hash.slice(1):'entry';$('#account').innerHTML=options([...state.accounts.map(a=>[a.id,a.name]),['__all__','全部帳戶 · 合併檢視']],combined?'__all__':account());$('.scope').hidden=page==='assets';$('#scope-label').textContent=combined?`合併檢視；新紀錄記入「${accountName(account())}」`:'資料只存在這台裝置';for(const a of $$('[data-page]')){if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}({entry:renderEntry,stocks:renderStocks,results:renderResults,assets:renderAssets}[page])();}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function makeEvent(form){const d=Object.fromEntries(new FormData(form)),previous=state.entries.find(r=>r.id===d.id),k=d.kind||form.dataset.kind,fx=k.startsWith('fx'),s=fx?{}:findStock(d.symbol,d.market||'auto');if(!fx&&!s.valid)throw Error('請改用有效股票代號，未知中文名稱不可直接記帳');const n=name=>{const v=Number(d[name]);if(d[name]===''||!Number.isFinite(v))throw Error('請填完整的金額／股數');return v;},e={id:previous?.id||uid(),kind:k,account:d.account,date:d.date,order:previous&&previous.date===d.date&&previous.account===d.account?previous.order:orderFor(d.date,d.account),notes:d.notes||''};if(fx)Object.assign(e,{usd:n('usd'),twd:n('twd'),fee:d.fee===''?0:n('fee')});else{Object.assign(e,s,{name:(s.market==='TW'?catalog[s.symbol]?.name:null)||(d.name||'').trim()||s.name});delete e.valid;if(['buy','sell'].includes(k)){Object.assign(e,{price:n('price'),quantity:n('quantity'),assetType:d.assetType==='auto'?s.assetType:d.assetType,broker:d.broker,category:d.category||previous?.category||''});const calculated=charges(e,state.brokers.find(b=>b.id===e.broker),state.settings.tax);e.fee=d.recalculate||d.fee===''?calculated.fee:n('fee');e.tax=d.recalculate||d.tax===''?calculated.tax:n('tax');}else if(k==='cash'){if(d.divMode==='perShare'){const profile=previous?.dividend&&!d.recalculateDividend?previous.dividend:state.brokers.find(b=>b.id===d.broker)?.dividends?.[s.market];if(!profile)throw Error('請先到券商設定確認此市場的股利扣款比例與費用');const detail=dividendAmount({perShare:n('perShare'),eligible:n('eligible'),rate:profile.rate,fee:profile.fee,other:Number(d.other||0),market:s.market});e.amount=detail.net;e.dividend=detail;e.broker=d.broker;if(d.exDate){day(d.exDate);if(d.exDate>d.date)throw Error('除息日不可晚於發放日');e.exDate=d.exDate;}e.destination=d.destination||'cash';}else e.amount=n('amount');e.destination=d.destination||'cash';}else if(k==='stock')e.quantity=n('quantity');else e.factor=n('factor');}return e;}
function formError(form,error){const p=$('[data-error]',form);if(p){p.textContent=error.message;p.hidden=false;p.tabIndex=-1;p.focus({preventScroll:true});p.scrollIntoView({block:'nearest'});}else message(error.message);}
document.addEventListener('submit',event=>{const form=event.target.closest('form[data-form]');if(!form)return;event.preventDefault();const d=Object.fromEntries(new FormData(form)),N=n=>{const v=Number(d[n]);if(!Number.isFinite(v)||v<0)throw Error('請填正確非負數字');return v;};try{const type=form.dataset.form;
 if(type==='period-prices'){const bounds=reportRange(reportMode,reportPeriod,reportStart,reportEnd,state.entries.filter(scoped).filter(e=>quoteKey(e)===reportStock));const prices={};for(const side of ['opening','ending'])if(d[side+'-price']){const close=N(side+'-price'),date=d[side+'-date'],limit=side==='opening'?priorDate(bounds.start):bounds.end;day(date);if(close<=0||date>limit)throw Error('股價須大於 0，行情日期不可晚於估值日');prices[side]={close,date,source:'本次手動試算'};}reportPrices[JSON.stringify([reportStock,bounds.start,bounds.end])]=prices;renderResults();return;}
 if(type==='entry'){const e=makeEvent(form),editing=form.dataset.edit==='true';commit(b=>{saveEvent(b,e);if(!editing){classifyPurchase(b,e);if(e.kind==='buy')b.settings.lastCategory=e.category||'';}if(e.market==='TW'&&catalog[e.symbol]&&(!b.quotes[quoteKey(e)]||catalog[e.symbol].date>=b.quotes[quoteKey(e)].date)){const q=catalog[e.symbol];b.quotes[quoteKey(e)]={close:q.close,date:q.date,change:q.change,source:q.source};}if(e.kind==='split'){const q=b.quotes[quoteKey(e)];if(q)q.review=splitPending(b,e.symbol,e.market,q.splits||[]);}},editing?revision:null);success=`${e.symbol||'換匯'} · ${kinds[e.kind]} · ${e.date}`;draft={};if(sheet.open)sheet.close();if(!editing&&e.kind==='cash'&&e.destination==='reinvest'){kind='buy';draft={symbol:e.symbol,account:e.account,broker:e.broker,notes:'股利再投入；來源 '+e.id};location.hash='entry';}render();message(e.destination==='reinvest'?'✓ 股利已存；請填實際成交價及股數，買入尚未儲存':'✓ 已儲存');void refresh(false,true);}
 else if(type==='cash-opening'||type==='cash-movement'){day(d.date);commit(b=>{const name=type==='cash-opening'?'cashOpenings':'cashMovements';b[name]??=[];if(type==='cash-movement'&&!b.cashOpenings?.some(o=>o.account===d.account&&o.currency===d.currency&&o.date<=d.date))throw Error('請先設定此帳戶／幣別的起始餘額，日期不可晚於這筆存提款');const r={id:d.id||uid(),account:d.account,currency:d.currency,date:d.date,amount:N('amount'),...(type==='cash-movement'?{direction:d.direction,notes:d.notes||''}:{})},i=b[name].findIndex(x=>x.id===r.id);b.history.unshift({id:uid(),at:new Date().toISOString(),entity:'現金',action:i<0?'新增':'修改',before:i<0?null:copy(b[name][i]),after:copy(r)});if(i<0)b[name].push(r);else b[name][i]=r;},revision);sheet.close();render();message('✓ 現金已儲存');}
 else if(type==='account'){commit(b=>{const name=d.name.trim();if(!name)throw Error('帳戶名稱不可空白');if(b.accounts.some(a=>a.name===name))throw Error('已有同名帳戶');const a={id:uid(),name,broker:d.broker};b.accounts.push(a);b.settings.account=a.id;});combined=false;sheet.close();render();}
 else if(type==='default-broker'){commit(b=>b.accounts.find(a=>a.id===account()).broker=d.broker);sheet.close();message('已儲存常用券商');}
 else if(type==='classification'){commit(b=>{const c={id:uid(),account:account(),market:form.dataset.market,symbol:form.dataset.symbol,category:d.category,bucket:d.bucket},i=b.classes.findIndex(x=>key(x)===key(c));if(i<0)b.classes.push(c);else b.classes[i]={...c,id:b.classes[i].id};},revision);sheet.close();render();}
 else if(type==='price'){day(d.date);commit(b=>b.quotes[form.dataset.key]={...b.quotes[form.dataset.key],close:N('close'),date:d.date,change:null,source:'手動收盤價'},revision);sheet.close();render();}
 else if(type==='asset'){commit(b=>{const a={id:d.id||uid(),name:d.name.trim(),account:d.account,bucket:d.bucket,currency:d.currency,amount:N('amount'),date:d.date},i=b.assets.findIndex(x=>x.id===a.id);b.history.unshift({id:uid(),at:new Date().toISOString(),entity:'資產',action:i<0?'新增':'更新',before:i<0?null:copy(b.assets[i]),after:copy(a)});if(i<0)b.assets.push(a);else b.assets[i]=a;},revision);sheet.close();render();}
 else if(type==='fx-rate'){day(d.date);if(d.date>today())throw Error('匯率日期不可在未來');commit(b=>{b.settings.fxMode='manual';b.settings.fx={rate:N('rate'),date:d.date};},revision);sheet.close();render();}
 else if(type==='fx-mode'){commit(b=>{b.settings.fxMode=d.mode;if(d.mode==='sinopac'&&bankQuote)applyFx(b.settings,bankQuote);},revision);sheet.close();render();void refresh(true);}
 else if(type==='targets'){const targets=Object.fromEntries(buckets.map((b,i)=>[b,N('target'+i)]));if(Math.abs(Object.values(targets).reduce((s,v)=>s+v,0)-100)>.01)throw Error('目標比例合計必須為 100%');commit(b=>{b.settings.targets=targets;b.settings.tolerance=N('tolerance');},revision);sheet.close();render();}
 else if(type==='category'){commit(b=>{const c={id:d.id,name:d.name.trim()};for(const f of ['profit','loss','rise','fall']){c[f]=d[f]===''?null:N(f);c[f+'Action']=d[f+'Action']||'note';}const i=b.settings.categories.findIndex(x=>x.id===c.id);if(i<0)b.settings.categories.push(c);else b.settings.categories[i]=c;},revision);sheet.close();render();}
 else if(type==='broker'){commit(b=>{const broker={id:d.id,name:d.name.trim(),tw:{rate:N('tw-rate')/100,discount:N('tw-discount')/10,min:N('tw-min'),round:d['tw-round']},us:{mode:d['us-mode'],rate:N('us-rate')/(d['us-mode']==='percent'?100:1),min:N('us-min'),extra:N('us-extra'),perShare:N('us-perShare'),sellRate:N('us-sellRate')/100,sellShare:N('us-sellShare'),sellMin:N('us-sellMin')}};broker.dividends={};for(const market of ['TW','US'])if(d['div-'+market+'-rate']!=='')broker.dividends[market]={rate:N('div-'+market+'-rate')/100,fee:N('div-'+market+'-fee')};const i=b.brokers.findIndex(x=>x.id===broker.id);if(i<0)b.brokers.push(broker);else b.brokers[i]=broker;b.settings.tax={stock:N('tax-stock')/100,etf:N('tax-etf')/100,day:N('tax-day')/100};},revision);sheet.close();render();}
 else if(type==='tiingo'){const previous=connection(),relay=relayOrigin(d.relay);if(relay&&!confirm(`Token 會送到 ${relay}，請確認這是你自己部署的中繼。`))return;const token=d.token.trim()||previous.token||'';if(token&&(/\s/.test(token)||token.length>512))throw Error('Token 格式無效');localStorage.setItem(storageKey+':connection',JSON.stringify({enabled:!!d.enabled,auto:!!d.auto,token,relay}));message('設定已儲存，請按測試確認連線');}
 else if(type==='plan'){commit(b=>{b.settings.plans??={};b.settings.plans[d.market]={symbol:d.symbol.trim().toUpperCase(),category:d.category};});revision=state.revision;message('已存記帳預設，不會自動產生成交');}
}catch(error){formError(form,error);}});
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;try{
 if(b.hasAttribute('data-dismiss-month')){commit(b=>b.settings.monthlyDismissed=today().slice(0,7));render();}
 else if(b.hasAttribute('data-categories'))open('分類與黃色提醒',state.settings.categories.map(c=>`<div class="record-top"><strong>${esc(c.name)}</strong><button class="text-link" data-category="${esc(c.id)}" type="button">設定提醒</button></div>`).join('')+'<button class="text-link" data-category="new" type="button">＋ 新增分類</button>');
 else if(b.hasAttribute('data-month-report')){reportStock='';reportMode='month';reportPeriod=b.dataset.monthReport;location.hash='results';render();}
 else if(b.dataset.kind){kind=b.dataset.kind;success='';draft={};renderEntry();}
 else if(b.hasAttribute('data-records'))recordsDialog();
 else if(b.dataset.edit){const e=state.entries.find(e=>e.id===b.dataset.edit);open('查看／修改紀錄',entryForm(e.kind,e,true)+`<button type="button" class="text-link" data-delete="${esc(e.id)}">刪除這筆紀錄</button>`);updateHint();}
 else if(b.dataset.delete){if(confirm('確定刪除？原內容保留，後續成本將重算。')){commit(d=>{deleteEvent(d,b.dataset.delete);for(const [k,q]of Object.entries(d.quotes))if(q.splits)q.review=splitPending(d,k.slice(3),k.slice(0,2),q.splits);},revision);sheet.close();render();}}
 else if(b.dataset.periodStep){const step=Number(b.dataset.periodStep);if(reportMode==='year')reportPeriod=String(Number(reportPeriod)+step);else{const d=new Date(reportPeriod+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+step);reportPeriod=d.toISOString().slice(0,7);}renderResults();}
 else if(b.dataset.stockReport){reportStock=b.dataset.stockReport;sheet.close();location.hash='results';render();}
 else if(b.dataset.stockTab)stockDialog(b.dataset.key,b.dataset.stockTab);
 else if(b.dataset.stock)stockDialog(b.dataset.stock);
 else if(b.dataset.quick){kind=b.dataset.quick;draft={symbol:b.dataset.symbol};success='';sheet.close();location.hash='entry';render();}
 else if(b.hasAttribute('data-refresh'))void refresh(true);
 else if(b.hasAttribute('data-cash'))open('現金帳',cashContent(ui));
 else if(b.dataset.cashEdit)open('起始現金',cashOpeningContent(ui,b.dataset.cashEdit));
 else if(b.dataset.cashDelete){if(confirm('刪除這筆存提款？原內容保留在變更紀錄。')){commit(d=>{const r=d.cashMovements.find(e=>e.id===b.dataset.cashDelete);d.history.unshift({id:uid(),at:new Date().toISOString(),entity:'現金',action:'刪除',before:copy(r),after:null});d.cashMovements=d.cashMovements.filter(e=>e.id!==r.id);},revision);open('現金帳',cashContent(ui));render();}}
 else if(b.hasAttribute('data-fx-records'))open('換匯紀錄與成本',fxContent({...ui,book:()=>calculate(state.entries.filter(r=>assetAccount==='__all__'||r.account===assetAccount))}));
 else if(b.hasAttribute('data-asset-add'))open('新增現金／其他資產',assetDialogContent(ui));
 else if(b.dataset.asset)open('更新資產餘額',assetDialogContent(ui,b.dataset.asset));
 else if(b.dataset.deleteAsset){if(confirm('刪除資產餘額？')){commit(d=>{const a=d.assets.find(x=>x.id===b.dataset.deleteAsset);d.history.unshift({id:uid(),at:new Date().toISOString(),entity:'資產',action:'刪除',before:copy(a),after:null});d.assets=d.assets.filter(x=>x.id!==b.dataset.deleteAsset);},revision);sheet.close();render();}}
 else if(b.hasAttribute('data-targets'))open('設定我的配置目標',targetContent(ui));
 else if(b.hasAttribute('data-brokers'))open('券商詳細費稅',brokerContent(ui,defaultBroker()));
 else if(b.dataset.category)open('分類與提醒門檻',categoryContent(ui,b.dataset.category));
 else if(b.hasAttribute('data-export'))download({...copy(state),exportedAt:new Date().toISOString()},`慢慢記備份-${today()}.json`);
 else if(b.hasAttribute('data-history'))open('修改／刪除前的內容',state.history.filter(h=>h.action!=='新增').map(h=>`<article class="record"><h3>${esc(h.entity)} · ${esc(h.action)}</h3><span class="meta">${esc(h.at)}</span><p>${esc(h.before?.symbol||h.before?.name||'')} ${esc(h.before?.date||'')}</p><p>${h.before?.price?`成交價 ${num(h.before.price)}，股數 ${num(h.before.quantity)}，費 ${num(h.before.fee)}，稅 ${num(h.before.tax)}`:esc(JSON.stringify(h.before))}</p></article>`).join('')||'<p class="empty">目前沒有修改或刪除紀錄。</p>');
 else if(b.hasAttribute('data-restore-snapshot')){const raw=localStorage.getItem(storageKey+':before-import');if(!raw)throw Error('尚無匯入前快照');const backup=validate(JSON.parse(raw));if(confirm('以快照還原？建議先匯出目前帳本。')){state=store.restore(backup);sheet.close();render();}}
 else if(b.hasAttribute('data-test-tiingo')){b.disabled=true;tiingoQuote('AAPL',connection()).then(()=>message('連線成功，可讀取美股日收盤')).catch(e=>message(e.message)).finally(()=>b.disabled=false);}
 else if(b.dataset.usePlan){const plan=state.settings.plans?.[b.dataset.usePlan];if(!plan?.symbol)throw Error('先儲存這個市場的預設股票');draft={...plan,market:b.dataset.usePlan};kind='buy';sheet.close();location.hash='entry';render();}
}catch(e){message(e.message);}});
document.addEventListener('input',event=>{const f=event.target.closest('[data-form="entry"]');if(f&&!sheet.open)draft=Object.fromEntries(new FormData(f));if(f){if(event.target.name==='symbol'&&f.elements.category){const p=findStock(f.elements.symbol.value),c=classOf({account:f.elements.account.value,...p});f.elements.category.value=c?.category||'';}updateHint();}});
document.addEventListener('change',async event=>{const e=event.target;try{
 const entryTarget=e.closest('[data-form="entry"]');if(entryTarget){updateHint();if(!sheet.open)draft=Object.fromEntries(new FormData(entryTarget));}
 if(e.id==='account'){if(e.value==='__all__')combined=true;else{commit(b=>b.settings.account=e.value);combined=false;}draft={};stockFilter='';if(reportStock&&!stockChoices().some(([k])=>k===reportStock))reportStock='';render();}
 else if(['date','account'].includes(e.name)&&e.closest('[data-form="entry"]')){const f=e.closest('form');if(f.dataset.edit!=='true'){f.elements.order.value=orderFor(f.elements.date.value,f.elements.account.value);if(e.name==='account'&&f.elements.broker)f.elements.broker.value=defaultBroker(e.value);draft=Object.fromEntries(new FormData(f));updateHint();}}
 else if(e.name==='exDate'&&entryTarget){if(e.value){day(e.value);const f=entryTarget,s=findStock(f.elements.symbol.value),p=calculate(state.entries.filter(r=>r.account===f.elements.account.value&&r.date<e.value)).positions.find(r=>quoteKey(r)===quoteKey(s));f.elements.eligible.value=p?.quantity||'';updateHint();if(!sheet.open)draft=Object.fromEntries(new FormData(f));}}
 else if(e.name==='held-symbol'){const f=e.closest('form');f.elements.symbol.value=e.value;updateHint();draft=Object.fromEntries(new FormData(f));}
 else if(e.name==='stock-market'){stockMarket=e.value;stockFilter='';renderStocks();}
 else if(e.name==='pie-basis'){pieBasis=e.value;renderStocks();}
 else if(e.name==='asset-account'){assetAccount=e.value;renderAssets();}
 else if(e.name==='stock-filter'){stockFilter=e.value;renderStocks();}
 else if(e.name==='records-stock')recordsDialog(e.value);
 else if(e.name==='report-stock'){reportStock=e.value;renderResults();}
 else if(e.name==='report-start'){reportStart=e.value;renderResults();}
 else if(e.name==='report-end'){reportEnd=e.value;renderResults();}
 else if(e.name==='report-mode'){reportMode=e.value;reportPeriod=today().slice(0,reportMode==='year'?4:7);renderResults();}
 else if(e.name==='report-period'){reportPeriod=e.value;if(reportMode==='year'&&!/^\d{4}$/.test(reportPeriod))return;renderResults();}
 else if(e.name==='kind'&&e.closest('[data-form="entry"]')){const f=e.closest('form'),d=Object.fromEntries(new FormData(f)),selected=e.value;if(sheet.open)open('查看／修改紀錄',entryForm(selected,d,true));else{kind=selected;draft=d;renderEntry();}}
 else if(e.name==='example'){const v=e.value.split(',');if(e.value)buckets.forEach((_,i)=>$(`[name="target${i}"]`).value=v[i]||0);}
 else if(e.name==='broker-picker')open('券商詳細費稅',brokerContent(ui,e.value));
 else if(e.name==='market'&&e.closest('[data-form="plan"]')){const plan=state.settings.plans?.[e.value]||{},f=e.closest('form');f.elements.symbol.value=plan.symbol||'';f.elements.category.value=plan.category||'';}
 else if(e.id==='backup-file'&&e.files[0]){const incoming=validate(JSON.parse(await e.files[0].text()));if(confirm(`備份含 ${incoming.entries.length} 筆帳務。將覆蓋目前帳本並保留匯入前快照，繼續？`)){state=store.restore(incoming);draft={};sheet.close();render();message('備份已完整匯入');}}
}catch(error){message(error.message);}});
$('#close-sheet').addEventListener('click',()=>sheet.close());$('#settings-button').addEventListener('click',()=>open('設定與備份',settingsContent(ui)));window.addEventListener('hashchange',()=>{if(state)render();});
function splitPending(b,symbol,market,splits){return splits.some(s=>calculate(b.entries.filter(e=>e.date<s.date)).positions.some(p=>p.symbol===symbol&&p.market===market&&p.quantity>0&&!b.entries.some(e=>e.account===p.account&&e.market===market&&e.symbol===symbol&&e.kind==='split'&&e.date===s.date&&e.factor===s.factor)));}
async function refresh(force=false,newEntry=false){
  if(!state)return;
  if(!navigator.onLine){updateQuoteStatus();if(force)message('離線中，已保留原行情；連網後會再檢查。');return;}
  if(busy||sheet.open)return;
  let last=0,attempt=0,lastUs=0;try{last=Number(sessionStorage.getItem(storageKey+':refresh')||0);attempt=Number(sessionStorage.getItem(storageKey+':refresh-attempt')||0);lastUs=Number(sessionStorage.getItem(storageKey+':us-refresh')||0);}catch{}
  if(!force&&!newEntry&&Date.now()-attempt<300000)return;
  if(!shouldRefresh({online:navigator.onLine,visible:force||document.visibilityState==='visible',busy,editing:sheet.open,last,force:force||newEntry}))return;
  busy=true;try{sessionStorage.setItem(storageKey+':refresh-attempt',String(Date.now()));}catch{}updateQuoteStatus();const failures=[];
  try{
    try{
      catalog=await loadCatalog();
      try{localStorage.setItem(storageKey+':catalog',JSON.stringify(catalog));}catch{failures.push('行情快取未儲存，請檢查裝置空間');}
      if(!sheet.open){
        const latest=store.read(),updates={};
        for(const q of Object.values(catalog)){
          const k='TW:'+q.symbol,next={close:q.close,date:q.date,change:q.change,source:q.source};
          if(latest.entries.some(e=>e.market==='TW'&&e.symbol===q.symbol)&&(!latest.quotes[k]||q.date>=latest.quotes[k].date)&&JSON.stringify(latest.quotes[k])!==JSON.stringify(next))updates[k]=next;
        }
        if(Object.keys(updates).length)commit(b=>Object.assign(b.quotes,updates));else state=latest;
      }
    }catch(e){failures.push(e.message);}
    try{bankQuote=await loadFx();if(!sheet.open&&fxMode(state.settings)==='sinopac'&&JSON.stringify(state.settings.fx)!==JSON.stringify({rate:bankQuote.buy,date:bankQuote.date,quotedAt:bankQuote.quotedAt,source:bankQuote.source}))commit(b=>applyFx(b.settings,bankQuote));}catch(e){if(fxMode(state.settings)==='sinopac')failures.push(e.message);}
    const c=connection();
    if(c.enabled&&(force||c.auto)&&!sheet.open&&(force||newEntry||Date.now()-lastUs>=3600000)){
      try{sessionStorage.setItem(storageKey+':us-refresh',String(Date.now()));}catch{}
      const symbols=[...new Set(calculate(state.entries).positions.filter(p=>p.market==='US'&&p.quantity>0).map(p=>p.symbol))];
      for(const s of symbols){
        if(sheet.open)break;
        try{
          const q=await tiingoQuote(s,c);if(sheet.open)break;
          commit(b=>{if(b.quotes['US:'+s]?.date>q.date)return;q.splits=[...new Map([...(b.quotes['US:'+s]?.splits||[]),...(q.splits||[])].map(x=>[x.date,x])).values()];q.review=splitPending(b,s,'US',q.splits);b.quotes['US:'+s]=q;});
        }catch(e){failures.push(s+'：'+e.message);}
      }
    }
    try{if(!failures.length&&!sheet.open)sessionStorage.setItem(storageKey+':refresh',String(Date.now()));}catch{}
  }catch(e){failures.push(e.message);}
  finally{busy=false;quoteError=failures.join('；');quoteChecked=new Date().toLocaleString('zh-TW',{hour12:false});if(page==='entry'){updateHint();updateQuoteStatus();}else if(!sheet.open&&document.activeElement?.closest('form'))updateQuoteStatus();else if(!sheet.open)render();if(force)message(failures.length?failures.join('；'):'可取得的日收盤價已更新；請核對每檔行情日期。');}
}
function boot(){try{state=store.read();try{catalog=JSON.parse(localStorage.getItem(storageKey+':catalog')||'{}');}catch{catalog={};}render();const month=today().slice(0,7),date=new Date(today()+'T00:00:00Z');date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()-1);const previous=date.toISOString().slice(0,7);if(state.settings.monthlySeen!==month&&state.entries.some(e=>e.date.startsWith(previous))){commit(b=>b.settings.monthlySeen=month);message(`${previous} 月報已可查看，到「成果」選擇月份。`);}void refresh();}catch(error){state=null;for(const id of ['settings-button','account'])$('#'+id).disabled=true;root.innerHTML=title('先保護你的紀錄','帳本暫停寫入',esc(error.message))+`<div class="paper"><p>不要清除瀏覽器資料。先下載原始內容保管，再還原可用的新版備份。</p><button id="rescue-download" class="secondary" type="button">下載原始救援檔</button><div class="field"><label for="rescue-import">還原慢慢記備份</label><input id="rescue-import" type="file" accept=".json"></div></div>`;$('#rescue-download').onclick=()=>download({raw:localStorage.getItem(storageKey)},`慢慢記救援-${today()}.json`);$('#rescue-import').onchange=async e=>{try{const b=validate(JSON.parse(await e.target.files[0].text()));if(confirm('請先下載救援檔。確定以備份還原？')){state=store.restore(b);location.reload();}}catch(error){message(error.message);}};}}
boot();document.addEventListener('visibilitychange',()=>{if(state&&document.visibilityState==='visible')void refresh();});window.addEventListener('online',()=>{if(state)void refresh();});window.addEventListener('storage',e=>{if(e.key===storageKey)message('另一分頁更新了帳本，請重新整理後再操作。');});
if(state)$('#launch-help').hidden=true;
const quoteTimer=setInterval(()=>{if(state)void refresh();},60000);
window.addEventListener('pageshow',()=>{if(state)void refresh();});
window.addEventListener('offline',updateQuoteStatus);
void installUpdates({notify:message,approve:()=>confirm('請先儲存本網站所有分頁的輸入內容；套用後會重新載入這個頁面，不會清除已存帳本。繼續？')});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'start_stock_entry',description:'預填買入／賣出表單，不儲存交易，仍需使用者確認。',inputSchema:{type:'object',properties:{symbol:{type:'string'},side:{enum:['buy','sell']}},required:['symbol','side'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.symbol!=='string'||!['buy','sell'].includes(input.side))throw Error('輸入無效');const s=findStock(input.symbol);if(!s.valid)throw Error('股票代號無效');draft={symbol:s.symbol,market:s.market};kind=input.side;location.hash='entry';render();return {status:'draft-opened',saved:false,symbol:s.symbol};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
function title(eyebrow,heading,sub='',button=''){return `<div class="page-heading"><div>${eyebrow?`<span class="eyebrow">${eyebrow}</span>`:''}<h1>${heading}</h1>${sub?`<p>${sub}</p>`:''}</div>${button}</div>`;}
function open(title,html){$('#sheet-title').textContent=title;const content=$('#sheet-content');content.innerHTML=html;revision=state.revision;if(!sheet.open)sheet.showModal();content.scrollTop=0;}
function defaultBroker(id=account()){return state.accounts.find(a=>a.id===id)?.broker||state.brokers[0].id;}
function orderFor(date,acct=account()){return Math.max(0,...state.entries.filter(e=>e.date===date&&e.account===acct).map(e=>e.order))+1;}
function findStock(raw,forced='auto'){return resolveStock(raw,forced,catalog,state.entries);}
function entryForm(k,d={},editing=false){
const fx=k.startsWith('fx'),trade=['buy','sell'].includes(k),div=['cash','stock','split'].includes(k),acct=d.account||account(),date=d.date||today(),formId=uid();
const inherited=d.symbol?classOf({account:acct,...findStock(d.symbol)})?.category:'';
const held=calculate(state.entries.filter(e=>e.account===acct)).positions.filter(p=>p.quantity>0);
return `<form data-form="entry" data-kind="${k}" data-edit="${editing}">
<input name="id" type="hidden" value="${esc(d.id||'')}"><input name="order" type="hidden" value="${d.order??orderFor(date,acct)}"><input name="name" type="hidden" value="${esc(d.name||'')}">${problem}
${div?field('股利種類','kind','text',k,[['cash','現金股利'],['stock','股票股利／配股'],['split','股票分割']]):fx?field('換匯方向','kind','text',k,[['fxbuy','台幣換美元'],['fxsell','美元換台幣']]):''}
<div class="entry-date">${field(div?'發放／生效日':fx?'換匯日':'成交日','date','date',date,null,true)}</div>
${!fx?`${k==='sell'&&!editing?field('從持股選擇','held-symbol','text',d.symbol||'',[['','選一檔持股'],...held.map(p=>[p.symbol,p.symbol+' '+p.name+' · 可賣 '+num(p.quantity)+' 股'])]):''}<div class="field"><label for="stock-${formId}">股票代號或名稱</label><input id="stock-${formId}" name="symbol" value="${esc(d.symbol||'')}" list="options-${formId}" placeholder="2330、台積電、AAPL" autocomplete="off" required><datalist id="options-${formId}" data-stock-options></datalist></div><p class="hint" data-stock-hint></p>`:''}
${trade?`<div class="row trade-row">${field('每股成交價','price','number',d.price??'',null,true)}${field('成交股數','quantity','number',d.quantity??'',null,true)}</div>`:k==='cash'?`${field('輸入方式','divMode','text',d.dividend?'perShare':d.amount!==undefined?'net':'perShare',[['perShare','每股配多少'],['net','直接填實收金額（舊紀錄／對帳）']])}<div data-div-per><div class="row">${field('每股現金股利','perShare','number',d.dividend?.perShare??d.perShare??'')}${field('符合配息資格股數','eligible','number',d.dividend?.eligible??d.eligible??'')}</div><p class="meta">請依除息資格核對股數，不是直接使用今天庫存。</p>${field('其他實扣款（含補充保費等）','other','number',d.dividend?.other??d.other??0)}</div><div data-div-net>${field('實際淨入帳','amount','number',d.amount??'')}</div>${field('收入用途','destination','text',d.destination||'cash',[['cash','進入現金'],['reinvest','再投入 · 下一步確認買入']])}`:k==='stock'?field('實際收到的配股股數','quantity','number',d.quantity??'',null,true):k==='split'?field('新股數 ÷ 原股數','factor','number',d.factor??'',null,true):`<div class="row">${field('美元金額','usd','number',d.usd??'',null,true)}${field('台幣金額（未含費用）','twd','number',d.twd??'',null,true)}</div>`}
<p class="hint fee-preview" data-fee-preview></p><details class="more"><summary>帳戶、費用與備註</summary>
${field('帳戶','account','text',acct,state.accounts.map(a=>[a.id,a.name]))}
${trade||k==='cash'?field('券商','broker','text',d.broker||defaultBroker(acct),state.brokers.map(b=>[b.id,b.name])):''}
${k==='cash'?`${field('除息日（選填，自動帶入前一日股數）','exDate','date',d.exDate||'')}${editing&&d.dividend?'<label class="radio-line"><input name="recalculateDividend" type="checkbox">用目前券商設定重算股利扣款</label><p class="meta">未勾选保留原扣款比例與入帳費。</p>':''}`:''}
${trade?`${field('稅別（通常不用改）','assetType','text',d.assetType||'auto',[['auto','依股票代號辨識'],['stock','一般股票'],['etf','一般／主動 ETF'],['bond','合資格被動債券 ETF'],['day','合資格現股當沖']])}<div class="row">${field('實付手續費（空白照券商）','fee','number',d.fee??'')}${field('實付稅費（空白照設定）','tax','number',d.tax??'')}</div>${editing?'<label class="radio-line"><input name="recalculate" type="checkbox">依目前券商設定重算費稅</label>':''}`:fx?field('手續費（TWD）','fee','number',d.fee??0):''}
${field('備註','notes','text',d.notes||'')}</details>
${k==='buy'?field('分類','category','text',d.category??inherited??'',[['','未分類'],...state.settings.categories.map(c=>[c.id,c.name])]):''}
<button class="primary" type="submit">${editing?'儲存修改':'記下這筆'+kinds[k]}</button></form>`;
}
function updateHint(){const f=$('[data-form="entry"]',sheet.open?sheet:root);if(!f?.elements.symbol)return;const d=Object.fromEntries(new FormData(f)),s=findStock(d.symbol,d.market||'auto'),q=s.market==='TW'?catalog[s.symbol]:state.quotes[quoteKey(s)];$('[data-stock-hint]',f).textContent=d.symbol?(s.valid?`${s.symbol} · ${s.name} · ${s.market==='TW'?'台股':'美股'}${s.assetType==='bond'?'／被動債券 ETF':s.assetType==='etf'?'／ETF':'／股票'}${q?` · ${q.date} 收盤 ${unitPrice(q.close,s.market)}`:s.market==='TW'?' · 尚未取得官方行情，請核對代號':' · 可選用 Tiingo 或手動股價'}`:'尚無法辨識，請改輸入股票代號'):'例如 2330、台積電、AAPL';if(s.valid&&s.market==='TW'&&catalog[s.symbol]&&f.elements.name)f.elements.name.value=catalog[s.symbol].name;const feeHint=$('[data-fee-preview]',f);if(feeHint){feeHint.textContent='';if(['buy','sell'].includes(f.dataset.kind)&&s.valid&&Number(d.price)>0&&Number(d.quantity)>0){try{const e={...s,kind:f.dataset.kind,date:d.date,price:Number(d.price),quantity:Number(d.quantity),assetType:d.assetType==='auto'?s.assetType:d.assetType},v=charges(e,state.brokers.find(b=>b.id===d.broker),state.settings.tax);feeHint.textContent=`${e.assetType==='bond'?'被動債券 ETF':e.assetType==='etf'?'ETF':e.assetType==='day'?'自選合資格當沖':'股票'} · 手續費 ${cash(d.recalculate||d.fee===''?v.fee:Number(d.fee),s.market)} · 稅費 ${cash(d.recalculate||d.tax===''?v.tax:Number(d.tax),s.market)}（空白按預設；實付優先）`;}catch{}}}if(f.dataset.kind==='cash'){const per=d.divMode==='perShare';$('[data-div-per]',f).hidden=!per;$('[data-div-net]',f).hidden=per;if(per){try{const old=state.entries.find(e=>e.id===d.id),profile=old?.dividend&&!d.recalculateDividend?old.dividend:state.brokers.find(b=>b.id===d.broker)?.dividends?.[s.market];if(!profile)feeHint.textContent='尚未設定此市場股利扣款：請到設定 → 券商詳細費稅。';else if(Number(d.perShare)>0&&Number(d.eligible)>0){const r=dividendAmount({perShare:Number(d.perShare),eligible:Number(d.eligible),rate:profile.rate,fee:profile.fee,other:Number(d.other||0),market:s.market});feeHint.textContent='應收 '+cash(r.gross,s.market)+' − 扣款 '+cash(r.withheld+r.fee+r.other,s.market)+' ＝ 實收 '+cash(r.net,s.market);}}catch(e){feeHint.textContent=e.message;}}}const text=d.symbol.normalize('NFKC').toLowerCase();$('[data-stock-options]',f).innerHTML=Object.values(catalog).filter(q=>text&&(q.symbol.toLowerCase().startsWith(text)||q.name.includes(text))).slice(0,20).map(q=>`<option value="${esc(q.symbol)}">${esc(q.name)}</option>`).join('');}
function recordRow(r){const amount=r.kind.startsWith('fx')?cash(r.usd,'US'):r.kind==='cash'?cash(r.amount,r.market):r.kind==='split'?`× ${r.factor}`:`${num(r.quantity)} 股`;return `<article class="record"><div class="record-top"><div><span class="tag">${kinds[r.kind]}</span><strong>${esc(r.symbol||'換匯')}</strong><small class="meta">${esc(r.date)} · ${esc(accountName(r.account))}</small></div><strong>${amount}</strong></div>${['buy','sell'].includes(r.kind)?`<p>成交價 ${unitPrice(r.price,r.market)} · 費稅 ${cash(r.fee+r.tax,r.market)}</p>`:''}<button class="text-link" type="button" data-edit="${esc(r.id)}">查看／修改這一筆</button></article>`;}
function stockChoices(){return [...new Map(state.entries.filter(scoped).filter(r=>r.symbol).map(r=>[quoteKey(r),[quoteKey(r),`${r.symbol} ${(r.market==='TW'?catalog[r.symbol]?.name:null)||r.name||''}`]])).values()];}
function recordsDialog(filter=''){const records=state.entries.filter(scoped).filter(r=>!filter||quoteKey(r)===filter).sort((a,b)=>b.date.localeCompare(a.date)||b.order-a.order);open('我的全部紀錄',field('找一檔股票','records-stock','text',filter,[['','全部紀錄（含換匯）'],...stockChoices()])+records.map(recordRow).join('')+(records.length?'':'<p class="empty">還沒有符合的紀錄。</p>'));}
function monthlyNotice(){const d=new Date(today()+'T00:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-1);const month=d.toISOString().slice(0,7);return state.settings.monthlyDismissed===today().slice(0,7)||!state.entries.some(e=>scoped(e)&&e.date.startsWith(month))?'':`<aside class="monthly-note"><span>${month} 月報已可查看</span><button class="text-link" type="button" data-month-report="${month}">查看上月成果 →</button><button class="quiet" type="button" data-dismiss-month>本月不再提醒</button></aside>`;}
function renderEntry(){root.innerHTML=title('','記帳','','<button class="text-link" data-records type="button">查看紀錄</button>')+`<section class="paper entry-paper compact-entry"><div class="tabs" aria-label="記帳種類">${[['buy','買入'],['sell','賣出'],['cash','股利'],['fxbuy','換匯']].map(([k,l])=>`<button type="button" data-kind="${k}" aria-pressed="${k===kind||(k==='cash'&&['stock','split'].includes(kind))||(k==='fxbuy'&&kind==='fxsell')}">${l}</button>`).join('')}</div>${entryForm(kind,draft)}</section>`;updateHint();}
function stockMetrics(p){const q=state.quotes[quoteKey(p)],valid=usable(q),pnl=valid?q.close*p.quantity-p.cost:null;return `<dl class="metrics"><div><dt>持有股數</dt><dd>${num(p.quantity)}</dd></div><div><dt>平均成本</dt><dd>${unitPrice(p.average,p.market)}</dd></div><div><dt>未實現損益</dt><dd class="${tone(pnl)}">${pnl===null?'尚缺股價':cash(pnl,p.market)}</dd></div><div><dt>持股報酬率</dt><dd class="${tone(pnl)}">${pnl!==null&&p.cost?pct(pnl/p.cost):'—'}</dd></div></dl>`;}
function pie(rows){const total=rows.reduce((s,[,v])=>s+v,0);if(!total)return '<p class="empty">還沒有可繪製的金額</p>';return `<div class="chart"><canvas width="400" height="400" data-values="${rows.map(([,v])=>v).join(',')}" role="img" aria-label="${esc(rows.map(([c,v])=>c+' '+pct(v/total)).join('、'))}"></canvas><ul class="legend">${rows.map(([c,v],i)=>`<li><span class="swatch color-${i%5}"></span><span>${esc(c)}</span><strong>${pct(v/total)}</strong></li>`).join('')}</ul></div>`;}
function draw(){for(const canvas of $$('canvas[data-values]')){const ctx=canvas.getContext('2d');if(!ctx)continue;const values=canvas.dataset.values.split(',').map(Number),total=values.reduce((a,b)=>a+b,0),colors=['#b86842','#d6a85f','#7a8d80','#a8a0bd','#cf9982'];let angle=-Math.PI/2;ctx.clearRect(0,0,400,400);values.forEach((v,i)=>{const end=angle+v/total*Math.PI*2;ctx.beginPath();ctx.moveTo(200,200);ctx.arc(200,200,180,angle,end);ctx.closePath();ctx.fillStyle=colors[i%5];ctx.fill();angle=end;});ctx.beginPath();ctx.arc(200,200,115,0,Math.PI*2);ctx.fillStyle='#fffdf9';ctx.fill();ctx.fillStyle='#79695d';ctx.textAlign='center';ctx.font='26px sans-serif';ctx.fillText('資金分布',200,210);}}
function renderStocks(){
const raw=book().positions,positions=combined?mergePositions(raw):raw,rows=positions.filter(p=>(stockMarket==='mixed'||p.market===stockMarket)&&(!stockFilter||quoteKey(p)===stockFilter)),values=new Map(),missing=[];
for(const p of raw.filter(p=>p.quantity>0&&(stockMarket==='mixed'||p.market===stockMarket))){const q=state.quotes[quoteKey(p)];if(pieBasis==='value'&&!usable(q)){missing.push(p.symbol+' 股價');continue;}let v=pieBasis==='cost'?p.cost:p.quantity*q.close;if(stockMarket==='mixed'&&p.market==='US'){if(!state.settings.fx){missing.push('美元匯率');continue;}v*=state.settings.fx.rate;}const c=categoryName(classOf(p)?.category);values.set(c,(values.get(c)||0)+v);}
root.innerHTML=title('','我的股票')+`<section class="paper"><div class="row compact-controls">${field('市場','stock-market','text',stockMarket,[['mixed','台美混合 · 台幣估值'],['TW','台股 · 台幣'],['US','美股 · 美元']])}${field('分類比例依據','pie-basis','text',pieBasis,[['value','目前市值'],['cost','持有成本']])}</div>${missing.length?'<p class="warning">缺少 '+esc([...new Set(missing)].join('、'))+'；圓餅圖暫不顯示，避免比例失真。</p>':pie([...values])}${stockMarket==='mixed'&&state.settings.fx?'<p class="meta">USD/TWD '+state.settings.fx.rate+' · '+esc(state.settings.fx.date)+'</p>':''}<button class="text-link" data-categories type="button">分類與提醒設定</button></section><div class="filters">${field('找股票','stock-filter','text',stockFilter,[['','全部（含已清倉）'],...stockChoices()])}<button class="text-link" data-records type="button">紀錄</button></div><div class="stock-list">${rows.map(p=>{const q=state.quotes[quoteKey(p)],valid=!p.quantity||usable(q),value=p.quantity?(valid?p.quantity*q.close:null):0,pnl=valid?value-p.cost:null,signals=raw.filter(r=>quoteKey(r)===quoteKey(p)).flatMap(r=>signal(r,state.quotes[quoteKey(r)],state.settings.categories.find(c=>c.id===classOf(r)?.category)));return `<article class="stock${signals.length?' signal':''}"><button class="stock-open" type="button" data-stock="${esc(quoteKey(p))}"><span><strong>${esc(p.symbol)} ${esc((p.market==='TW'?catalog[p.symbol]?.name:null)||p.name)}</strong><small>${p.quantity?'市值 '+cash(value,p.market):'已清倉'}</small></span><span class="${tone(pnl)}">${cash(pnl,p.market)}<small>${pnl!==null&&p.cost?pct(pnl/p.cost):'—'} ›</small></span></button>${signals.length?'<p class="warning">'+esc([...new Set(signals)].join('；'))+'</p>':''}</article>`;}).join('')||'<p class="empty">沒有符合的股票</p>'}</div><div data-quote-status>${priceStatus()}</div>`;draw();
}
function stockDialog(qk,tab='summary'){const b=book(),events=b.results.filter(r=>quoteKey(r)===qk),positions=b.positions.filter(p=>quoteKey(p)===qk),p=mergePositions(positions)[0];if(!p)return;const c=combined?null:classOf(positions[0]);const sales=events.filter(e=>e.kind==='sell'),cost=sales.reduce((n,e)=>n+e.allocated,0),wins=sales.filter(e=>e.pnl>0).length;
const tabs=`<div class="tabs">${[['summary','操作成果'],['history','交易紀錄'],['manage','管理']].map(([id,label])=>`<button type="button" data-stock-tab="${id}" data-key="${esc(qk)}" aria-pressed="${tab===id}">${label}</button>`).join('')}</div>`;
const summary=`<div class="summary-grid">${metric('累計已實現',cash(p.realized,p.market),'已扣交易費稅',p.realized)}${metric('已售成本報酬率',cost?pct(p.realized/cost):'尚未賣出','已實現 ÷ 賣出配對成本',p.realized)}</div><p class="meta">共賣出 ${sales.length} 筆 · 獲利 ${wins} 筆 · 淨股利 ${cash(p.dividend,p.market)}</p><details class="more"><summary>目前持股與成本</summary>${stockMetrics(p)}</details><button class="primary" type="button" data-stock-report="${esc(qk)}">選期間看這檔成果</button><div class="actions"><button class="text-link" type="button" data-quick="buy" data-symbol="${esc(p.symbol)}">買入</button><button class="text-link" type="button" data-quick="sell" data-symbol="${esc(p.symbol)}">賣出</button><button class="text-link" type="button" data-quick="cash" data-symbol="${esc(p.symbol)}">＋ 股利／配股</button></div>${combined?'<p class="meta">新增記入目前預設帳戶，可在記帳表內修改。</p>':''}`;
const history=events.slice().reverse().map(e=>`<article class="record"><span class="meta">${esc(e.date)} · ${esc(accountName(e.account))}</span><strong>${kinds[e.kind]} ${e.kind==='cash'?cash(e.amount,e.market):e.kind==='split'?'×'+e.factor:num(e.quantity)+' 股'}</strong>${e.kind==='sell'?`<p class="${tone(e.pnl)}">已實現 ${cash(e.pnl,e.market)} · 報酬率 ${pct(e.returnRate)}</p>`:''}<p class="meta">操作後 ${num(e.afterQuantity)} 股 · 均價 ${unitPrice(e.average,e.market)}</p><button class="text-link" data-edit="${esc(e.id)}" type="button">修改</button></article>`).join('');
const manage=(combined?'<p>請先選單一帳戶修改分類。</p>':`<form data-form="classification" data-symbol="${esc(p.symbol)}" data-market="${p.market}">${field('股票分類','category','text',c?.category||'',[['','未分類'],...state.settings.categories.map(c=>[c.id,c.name])])}${field('資產配置類別','bucket','text',c?.bucket||(p.market==='TW'?'台股':'美股'),buckets.map(x=>[x,x]))}${problem}<button class="secondary" type="submit">更新分類</button></form>`)+`<details class="more"><summary>手動收盤價</summary><form data-form="price" data-key="${esc(qk)}">${field('收盤價','close','number',state.quotes[qk]?.close||'',null,true)}${field('行情日期','date','date',state.quotes[qk]?.date||today(),null,true)}${problem}<button class="secondary" type="submit">儲存</button></form></details>`;
open(p.symbol+' · '+((p.market==='TW'?catalog[p.symbol]?.name:null)||p.name),tabs+(tab==='summary'?summary:tab==='history'?history:manage));}

function metric(label,value,note='',t=0){return `<div class="metric-box"><span>${label}</span><strong class="${tone(t)}">${value}</strong>${note?`<p>${note}</p>`:''}</div>`;}
function renderResults(){root.innerHTML=resultView({entries:state.entries.filter(scoped),stock:reportStock,mode:reportMode,period:reportPeriod,start:reportStart,end:reportEnd,field,esc,cash,pct,metric,tone,choices:stockChoices(),quotes:state.quotes,prices:reportPrices,accountName,fx:state.settings.fx});fitMonthlyCharts(root);}
// Resize only the chart: never replace a form while someone is typing.
if(typeof ResizeObserver!=='undefined')new ResizeObserver(()=>fitMonthlyCharts(root)).observe(root);
else window.addEventListener('resize',()=>fitMonthlyCharts(root));
