import {cashBalances} from './cash.js';
import {fxMode,SINOPAC_PAGE} from './fx.js';
import {key,quoteKey,usable,day,today,uid} from './book.js';
export function assetView(u){const {state,book,classOf,scoped,buckets,pie,cash,pct,esc}=u,values=new Map(buckets.map(b=>[b,0])),missing=[],dates=[],auto=cashBalances(state).filter(scoped),assets=state.assets.filter(scoped).filter(a=>a.bucket!=='現金'||!auto.some(o=>o.account===a.account&&o.currency===a.currency)),fx=state.settings.fx;function add(bucket,value,currency,date){if(currency==='USD'&&!fx){missing.push('美元估值匯率');return;}values.set(bucket,values.get(bucket)+value*(currency==='USD'?fx.rate:1));dates.push(date);}for(const p of book().positions.filter(p=>p.quantity>0)){const q=state.quotes[quoteKey(p)];if(!usable(q)){missing.push(p.symbol+' 股價');continue;}const type=state.entries.find(e=>key(e)===key(p))?.assetType;add(classOf(p)?.bucket||(type==='bond'?'債券':p.market==='TW'?'台股':'美股'),p.quantity*q.close,p.market==='US'?'USD':'TWD',q.date);}for(const a of auto){add('現金',Math.max(0,a.amount),a.currency,a.date);if(a.amount<0)missing.push(a.currency+' 現金為負，請對帳（圖中暫以 0 顯示）');}for(const a of assets)add(a.bucket,a.amount,a.currency,a.date);for(const a of state.accounts.filter(a=>scoped({account:a.id})))for(const currency of ['TWD','USD'])if(!assets.some(x=>x.account===a.id&&x.bucket==='現金'&&x.currency===currency)&&!auto.some(x=>x.account===a.id&&x.currency===currency))missing.push(`${a.name} 的 ${currency} 現金餘額（沒有可填 0）`);const rows=[...values],total=rows.reduce((s,[,v])=>s+v,0),targets=state.settings.targets,valid=Math.abs(Object.values(targets).reduce((s,v)=>s+v,0)-100)<.01;
return `<section class="paper"><span class="meta">${missing.length?'已知部分資產':'已記錄資產'} · 台幣估值</span><h2 class="amount-title">${cash(total)}</h2>${pie(rows)}${missing.length?`<p class="warning">還缺 ${esc([...new Set(missing)].join('、'))}。補齊前不計算配置調整。</p>`:''}<p class="meta">只含已登錄資產，不含未記錄資產或負債。${fx?`USD/TWD ${fx.rate} · ${esc(fx.quotedAt||fx.date)} · ${esc(fx.source||'手動匯率')}。`:''}${dates.some(d=>day(today())-day(d)>7)?'部分估值超過 7 天，請更新。':''}</p></section><section class="panel"><div class="record-top"><h2>離我想要的比例，還差多少？</h2><button class="text-link" data-targets type="button">設定目標</button></div>${!valid?'<p>先選擇配置範例，再改成自己的目標。</p>':missing.length||total<=0?'<p>請先補齊資料及正資產餘額，再查看調整差額。</p>':rows.map(([b,v])=>{const actual=total?v/total*100:0,target=targets[b]||0,adjust=total*target/100-v,alert=Math.abs(actual-target)>state.settings.tolerance;return `<div class="allocation-row${alert?' signal':''}"><div class="record-top"><strong>${b}</strong><span>${pct(actual/100)} / 目標 ${target}%</span></div><p>${adjust>=0?'距目標可增加':'距目標可減少'} ${cash(Math.abs(adjust))}${alert?' · 超過自訂偏差':''}</p></div>`;}).join('')}<p class="meta">這是你設定的比例差額，未計費稅；不是自動買賣建議或收益保證。</p></section><button class="secondary" data-fx-records type="button">換匯紀錄與成本</button><section class="panel"><h2>現金與其他資產</h2><button class="text-link" data-cash type="button">管理現金 · 起始餘額／存提款</button>${auto.map(a=>`<article class="record${a.amount<0?' signal':''}"><div class="record-top"><strong>${esc(u.accountName(a.account))} · ${a.currency}</strong><span>${cash(a.amount,a.currency)}</span></div><span class="meta">自動現金 · 起算 ${a.openingDate}</span></article>`).join('')}<p class="meta">現金按交易日記帳，非券商交割／可提領餘額。其他資產用金額快照，可隨時修改；啟用自動現金的帳戶／幣別不再重複加計舊現金快照。</p>${assets.map(a=>`<article class="record"><div class="record-top"><strong>${esc(a.name)}</strong><span>${cash(a.amount,a.currency)}</span></div><span class="meta">${esc(u.accountName(a.account))} · ${a.bucket} · ${esc(a.date)}</span><button class="text-link" type="button" data-asset="${esc(a.id)}">更新／刪除</button></article>`).join('')||(auto.length?'':'<p class="empty">尚無現金或其他資產</p>')}<button class="text-link" data-asset-add type="button">＋ 新增資產</button></section>`;}
export function assetDialogContent(u,id=''){const {state,field,esc,problem}=u,a=state.assets.find(x=>x.id===id)||{};return `<form data-form="asset"><input name="id" type="hidden" value="${esc(id)}">${problem}${field('資產名稱','name','text',a.name||'',null,true)}<div class="row">${field('配置類別','bucket','text',a.bucket||'現金',u.buckets.map(x=>[x,x]))}${field('幣別','currency','text',a.currency||'TWD',[['TWD','台幣'],['USD','美元']])}</div><div class="row">${field('目前餘額','amount','number',a.amount??'',null,true)}${field('餘額日期','date','date',a.date||today(),null,true)}</div>${field('帳戶','account','text',a.account||u.account(),state.accounts.map(a=>[a.id,a.name]))}<button class="primary" type="submit">儲存這份餘額</button>${id?`<button type="button" class="text-link" data-delete-asset="${esc(id)}">刪除資產</button>`:''}</form><hr class="divider"><h3>美元估值匯率</h3><p class="meta">美元折回台幣採銀行即期買入價；銀行賣出價才是你買美元的參考。自動模式讀取 GitHub 發布時的永豐牌告快照，不是即時換匯成交價，不改寫歷史換匯。</p><form data-form="fx-mode">${field('估值匯率來源','mode','text',fxMode(state.settings),[['sinopac','自動 · 永豐即期買入'],['manual','手動 · 我的參考匯率']])}${problem}<button class="secondary" type="submit">儲存匯率模式</button></form><p><a href="${SINOPAC_PAGE}" target="_blank" rel="noopener noreferrer">查看永豐最新牌告 ↗</a></p><p class="meta">手動儲存下方數值會切換成手動模式，自動更新不會覆蓋它。</p><form data-form="fx-rate"><div class="row">${field('1 USD = TWD','rate','number',state.settings.fx?.rate||'',null,true)}${field('匯率日期','date','date',state.settings.fx?.date||today(),null,true)}</div>${problem}<button class="secondary" type="submit">更新估值匯率</button></form>`;}
export function targetContent(u){const {field,state,buckets,problem}=u;return `<p>範例僅供自行調整，未依你的財務狀況個人化推薦。</p>${field('範例：台股／美股／債券／現金','example','text','',[['','自行設定'],['20,20,40,20','範例 A · 20／20／40／20'],['20,40,30,10','範例 B · 20／40／30／10'],['30,50,15,5','範例 C · 30／50／15／5']])}<form data-form="targets"><div class="row">${buckets.map((b,i)=>field(`${b}目標（%）`,'target'+i,'number',state.settings.targets[b]||0,null,true)).join('')}</div>${field('容許偏差（百分點）','tolerance','number',state.settings.tolerance,null,true)}${problem}<button class="primary" type="submit">套用我的目標</button><p class="meta">合計需 100%，提醒只出現在資產頁。</p></form>`;}
export function settingsContent(u){const {state,field,problem,esc}=u,c=u.connection();return `<details class="panel" open><summary>帳戶與常用券商</summary><form data-form="default-broker"><div class="row">${field('預設帳戶','default-account','text',u.account(),state.accounts.map(a=>[a.id,a.name]))}${field('預設券商','broker','text',u.defaultBroker(),state.brokers.map(b=>[b.id,b.name]))}</div>${problem}</form><div class="actions settings-add"><button class="secondary" type="button" data-account-add>＋ 新增帳戶</button><button class="secondary" type="button" data-broker-add>＋ 新增券商</button></div><button class="text-link" data-brokers type="button">詳細設定台股／美股費稅 →</button></details><details class="panel"><summary>分類與黃色提醒</summary><p>每個分類可設定報酬率／日漲跌門檻，並指定買入觀察或賣出觀察。達門檻時持股卡片變黃，不會自動下單。</p>${state.settings.categories.map(c=>`<div class="record-top"><span>${esc(c.name)}</span><button class="text-link" data-category="${esc(c.id)}" type="button">修改門檻</button></div>`).join('')}<button class="text-link" data-category="new" type="button">＋ 新增分類</button></details><details class="panel"><summary>備份、換手機與變更紀錄</summary><p>定期匯出；清除網站資料、私密瀏覽或換手機可能遺失帳本。備份不含 Token。</p><div class="actions"><button class="secondary" data-export type="button">匯出備份</button><button class="secondary" data-restore-snapshot type="button">還原匯入前</button></div><div class="field"><label for="backup-file">匯入慢慢記新版備份</label><input id="backup-file" type="file" accept=".json,application/json"></div><p class="meta">新資料格式，不會自動讀取或覆蓋舊版。舊備份請保留。</p><button class="text-link" data-history type="button">查看修改／刪除前內容</button></details><details class="panel"><summary>Tiingo 美股備援（選用）</summary><p>只更新日收盤，不是即時價。預設關閉。GitHub Pages 直接連線可能受限，可自行部署隨附中繼。不要使用陌生中繼，它會收到 Token。</p><form data-form="tiingo"><label class="radio-line"><input name="enabled" type="checkbox"${c.enabled?' checked':''}>啟用美股行情備援</label>${field('API Token（空白保留已存值）','token','password','')}${field('自有中繼 HTTPS 網址（選填）','relay','url',c.relay||'')}<label class="radio-line"><input name="auto" type="checkbox"${c.auto!==false?' checked':''}>連網自動更新日收盤</label>${problem}<button class="secondary" type="submit">儲存連線設定</button><button class="text-link" data-test-tiingo type="button">測試已儲存的連線</button></form></details><details class="panel"><summary>定期定額記帳預設</summary><p>只預填表單，不會把計畫當已成交。實際成交價與股數仍由你確認。</p><form data-form="plan">${field('市場','market','text','TW',[['TW','台股'],['US','美股']])}${field('常用代號','symbol','text',state.settings.plans?.TW?.symbol||'')}${field('分類','category','text',state.settings.plans?.TW?.category||'',[['','未分類'],...state.settings.categories.map(c=>[c.id,c.name])])}${problem}<button class="secondary" type="submit">儲存市場預設</button></form><div class="actions"><button class="text-link" data-use-plan="TW" type="button">台股預設記一筆</button><button class="text-link" data-use-plan="US" type="button">美股預設記一筆</button></div></details>`;}
export function brokerContent(u,id){const {state,field,problem,esc}=u,old=state.brokers.find(b=>b.id===id),b=old||state.brokers[0];return `${field('選擇券商','broker-picker','text',old?.id||'new',[...state.brokers.map(b=>[b.id,b.name]),['new','＋ 新增券商']])}<form data-form="broker"><input name="id" type="hidden" value="${esc(old?.id||uid())}">${field('券商名稱','name','text',old?.name||'',null,true)}<details class="panel" open><summary>台股手續費與稅率</summary><div class="row">${field('基本費率（%）','tw-rate','number',b.tw.rate*100,null,true)}${field('折數（例：2.8 折）','tw-discount','number',b.tw.discount*10,null,true)}${field('最低費（TWD）','tw-min','number',b.tw.min,null,true)}${field('手續費小數處理','tw-round','text',b.tw.round,[['round','四捨五入'],['floor','捨去'],['ceil','進位']])}${field('交易稅小數處理','tw-tax-round','text',b.tw.taxRound||'round',[['round','四捨五入'],['floor','捨去'],['ceil','進位']])}${field('股票稅率（%）','tax-stock','number',state.settings.tax.stock*100,null,true)}${field('一般 ETF 稅率（%）','tax-etf','number',state.settings.tax.etf*100,null,true)}${field('合資格當沖（%）','tax-day','number',state.settings.tax.day*100,null,true)}</div><p class="meta">取整依你的券商明細設定，不更動舊交易。合資格被動債券 ETF 停徵至 2026-12-31；主動／槓桿／反向不適用。稅率全帳本共用；當沖優惠到期後依普通股票試算。請核對交易當時規定。</p></details><details class="panel" open><summary>美股手續費與賣出稅費</summary>${field('主要計費方式','us-mode','text',b.us.mode,[['fixed','每筆固定 USD'],['share','每股 USD'],['percent','成交額百分比']])}<div class="row">${field('費率／金額（百分比填 %）','us-rate','number',b.us.rate*(b.us.mode==='percent'?100:1),null,true)}${[['min','最低基本費'],['extra','另外每筆費'],['perShare','另外每股費'],['sellRate','賣出稅費率（%）'],['sellShare','賣出每股稅費'],['sellMin','賣出稅費最低額']].map(([f,l])=>field(l,'us-'+f,'number',b.us[f]*(f==='sellRate'?100:1),null,true)).join('')}</div><p class="meta">初始 0 不代表必然免稅。可加總每筆／每股費；複雜分項進位或上限請用實付覆寫。金額單位 USD。</p></details><details class="panel"><summary>現金股利扣款設定</summary><p class="meta">請按你的券商入帳單確認；留白表示尚未設定，填 0 表示你確認不扣。ETF 所得組成、稅籍及補充保費可能不同，不套用統一稅率。</p>${['TW','US'].map(m=>`<h3>${m==='TW'?'台股 TWD':'美股 USD'}</h3><div class="row">${field('股利預扣比例（%）','div-'+m+'-rate','number',b.dividends?.[m]?.rate===undefined?'':b.dividends[m].rate*100)}${field('每次入帳費用','div-'+m+'-fee','number',b.dividends?.[m]?.fee??0)}</div>`).join('')}<p class="meta">補充保費等額外實扣款在股利紀錄另填；這不是年度所得稅試算。</p></details><label class="radio-line"><input name="use-default" type="checkbox"${!old||old.id===u.defaultBroker()?' checked':''}>設為目前帳戶的預設券商</label>${problem}<button class="primary" type="submit">儲存券商費稅</button><p class="meta">新交易套用；舊紀錄有費稅差異時，會在「我的股票」提醒你確認是否批次更新。</p></form>`;}
export function categoryContent(u,id){
  const c=u.state.settings.categories.find(x=>x.id===id)||{id:uid(),name:''};
  return `<form data-form="category"><input name="id" type="hidden" value="${u.esc(c.id)}">${u.field('分類名稱','name','text',c.name,null,true)}
  ${[['profit','持股獲利報酬率達（%）','sell'],['loss','持股虧損幅度達（%）','buy'],['rise','當日上漲幅度達（%）','sell'],['fall','當日下跌幅度達（%）','buy']].map(([f,l,action])=>`<div class="threshold-row">${u.field(l,f,'number',c[f]??'')}${u.field('觸發時標示',f+'Action','text',c[f+'Action']||action,[['buy','買入觀察'],['sell','賣出觀察'],['note','只提醒']])}</div>`).join('')}
  <p class="meta">幅度填正數；留空／0 關閉。報酬率＝（持股市值 − 含買進費用的成本）÷ 成本，不含股息與預估賣出費。當日漲跌依行情交易日；美股以紐約交易日期判定。旧價不觸發今日訊號。已清倉不提醒。</p>
  <p class="meta">黃色是你自訂的觀察提醒，不代表程式判斷適合買賣。此分類的各檔持股各自比較門檻；不是把整類報酬平均。</p>
  ${u.problem}<button class="primary" type="submit">儲存分類與提醒</button></form>`;
}

export function cashContent(u){
const {state,field,esc,cash,problem}=u,balances=cashBalances(state);
return `<h3>起始現金</h3><p class="meta">填「起算日開始前」的餘額；當日起的買賣、股利、換匯及存提款自動加減。不改舊交易或刪除舊快照。台幣、美元分別設定。</p>
${balances.map(a=>`<div class="record"><strong>${esc(u.accountName(a.account))} · ${a.currency} ${cash(a.amount,a.currency)}</strong><p class="meta">${a.openingDate} 期初 ${cash(a.opening,a.currency)}</p><button class="text-link" data-cash-edit="${esc(a.id)}" type="button">修改期初</button></div>`).join('')}
<button class="secondary" data-cash-edit="new" type="button">設定起始餘額</button><hr class="divider"><h3>存入／提出現金</h3><form data-form="cash-movement">${field('帳戶','account','text',u.account(),state.accounts.map(a=>[a.id,a.name]))}<div class="row">${field('幣別','currency','text','TWD',[['TWD','台幣'],['USD','美元']])}${field('方向','direction','text','in',[['in','存入'],['out','提出']])}</div><div class="row">${field('金額','amount','number','',null,true)}${field('日期','date','date',today(),null,true)}</div>${field('備註','notes','text','')}${problem}<button class="primary" type="submit">記錄存提款</button></form><details class="more"><summary>存提款紀錄</summary>${(state.cashMovements||[]).slice().sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<article class="record">${esc(e.date)} · ${esc(u.accountName(e.account))}<p>${e.direction==='in'?'存入':'提出'} ${cash(e.amount,e.currency)} · ${esc(e.notes)}</p><button class="text-link" data-cash-delete="${esc(e.id)}" type="button">刪除錯誤紀錄</button></article>`).join('')}</details>`;
}
export function cashOpeningContent(u,id){
const a=u.state.cashOpenings?.find(a=>a.id===id)||{}, {field,esc,state}=u;
return `<form data-form="cash-opening"><input name="id" type="hidden" value="${esc(a.id||'')}">${field('帳戶','account','text',a.account||u.account(),state.accounts.map(a=>[a.id,a.name]))}${field('幣別','currency','text',a.currency||'TWD',[['TWD','台幣'],['USD','美元']])}${field('起算日（當日開始前餘額）','date','date',a.date||today(),null,true)}${field('起始現金','amount','number',a.amount??'',null,true)}<p class="meta">若填今天，請填昨天結束時的現金；今天已記交易會再自動加減。舊現金快照保留但不重複加總。</p>${u.problem}<button class="primary" type="submit">儲存起始餘額</button></form>`;
}

export function fxContent(u){const {state,book,cash,esc}=u,fx=state.settings.fx;return `<details class="panel" open><summary>我的換匯成本筆記</summary><p class="meta">依買入／賣出美元紀錄加權，不扣除股票交易用掉的美元，因此不是帳戶現金餘額。</p>${book().fx.map(f=>`<article class="record"><strong>${esc(u.accountName(f.account))}</strong><p>未配對賣匯的美元 ${cash(f.usd,'USD')} · 平均買匯成本 ${f.usd?(f.cost/f.usd).toFixed(4):'—'}</p>${u.bankQuote&&f.usd?`<p>平均買匯成本 ${(f.cost/f.usd).toFixed(4)}，最近永豐即期賣出牌告 ${u.bankQuote.sell.toFixed(4)} · ${esc(u.bankQuote.quotedAt)}。你的歷史平均成本${f.cost/f.usd<u.bankQuote.sell?'較低':'較高或相同'}；不是成交當日優惠比較。</p>`:''}<p>累計賣匯損益 ${cash(f.realized)}${fx&&f.usd?` · 以目前參考匯率估算價差 ${cash(f.usd*fx.rate-f.cost)}`:''}</p></article>`).join('')||'<p class="empty">到記帳頁選「換匯」開始記錄。</p>'}</details>`;}
