import {swingResult} from './swing.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>v===null?'—':new Intl.NumberFormat('zh-TW',{maximumFractionDigits:2}).format(v);
export function swingSettings(state){return `<details class="panel"><summary>擴充功能：波段交易計畫</summary><p>選用功能，預設關閉。停用保留記事本與計畫；隨帳本備份。</p><form data-form="swing-toggle"><label class="radio-line"><input name="enabled" type="checkbox"${state.settings.swing?.enabled?' checked':''}>啟用波段記事本與 R 提示</label><button class="secondary" type="submit">儲存擴充設定</button></form></details>`;}
export function swingDashboard(state,account,combined=false,catalog={}){
  if(!state.settings.swing?.enabled)return '';
  const plans=state.settings.swing.plans.filter(p=>(combined||p.account===account)&&!p.closed);
  return `<section class="panel"><h2>波段交易計畫</h2><p class="meta">日收盤檢視，非盤中監控；關閉網站不會推播或下單。</p><button class="secondary" type="button" data-swing-new>＋ 個股買進記事本</button>${plans.map(p=>{
    const saved=state.quotes['TW:'+p.symbol],publicQuote=catalog[p.symbol],q=saved&&(!publicQuote||saved.date>=publicQuote.date)?saved:publicQuote,r=swingResult(p,q&&!q.review&&q.date>=p.entryDate?q.close:null);
    return `<article class="record"><strong>${esc(p.symbol)} · ${esc(state.accounts.find(a=>a.id===p.account)?.name||'原帳戶')} · ${n(r.r)} R</strong><p>${esc(r.notice)}</p><p>＋${n(p.trigger)}R 目標 ${n(r.target)} 元 · 計畫停損 ${n(r.protective)} 元</p><p class="meta">${q?esc(q.date)+' 收盤 '+n(q.close)+' 元':'尚無收盤行情'}${q?.review?'；行情待確認，暫停 R 判讀':''}${q&&q.date<p.entryDate?'；行情早於計畫買進日，不計 R':''}。僅此行情時點，無法判斷盤中是否曾觸價。</p><button class="text-link" type="button" data-swing-edit="${esc(p.id)}">查看／更新記事本</button></article>`;
  }).join('')}<details class="more"><summary>已結束計畫</summary>${state.settings.swing.plans.filter(p=>(combined||p.account===account)&&p.closed).map(p=>`<button class="text-link" type="button" data-swing-edit="${esc(p.id)}">${esc(p.symbol)} · 查看記事本</button>`).join('')||'尚無紀錄'}</details></section>`;
}
export function swingForm(u,p=null){
  const b=u.state.brokers.find(b=>b.id===u.defaultBroker()),f=u.field;
  const values=p||{entry:'',stop:'',quantity:'',trigger:1.5,buyFee:'',feeRate:b.tw.rate*b.tw.discount,minimumFee:b.tw.min,taxRate:u.state.settings.tax.stock,sold:0,high:0,protectedStop:0};
  const input=(label,k)=>f(label,k,'number',values[k],null,true).replace('<input ',`<input step="any" ${p&&['entry','stop','quantity','trigger'].includes(k)?'readonly ':''}`);
  return `<form data-swing-editor><input type="hidden" name="id" value="${esc(p?.id||'')}"><p class="meta">台股個股、現金一次買進。獨立計畫，不會新增買賣紀錄；加碼、分割或新一輪交易請結束舊計畫後另建。</p>${f('買進／預計買進日','entryDate','date',p?.entryDate||new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei'}).format(new Date()),null,true).replace('<input ',`<input ${p?'readonly ':''}`)}${f('股票代號','symbol','text',p?.symbol||'',null,true).replace('<input ',`<input ${p?'readonly ':''}`)}<div class="row">${input('實際／預計買進價','entry')}${input('原始停損價','stop')}</div><div class="row">${input('原始股數','quantity')}${input('分批門檻（R）','trigger')}</div><p class="meta">1R＝買進價－原始停損；儲存後固定，不隨停損上移重算。</p><div class="field"><label for="swing-notes">買進理由／停損依據／操作記事</label><textarea id="swing-notes" name="notes" rows="4" maxlength="4000">${esc(p?.notes||'')}</textarea></div><details class="more" open><summary>費用與保本試算（買進費必填）</summary><p class="meta">買進費必填，請填實付或自行預估；其餘帶入建立時券商設定。費率為小數，如 0.001425；最低費須核對零股。賣出費稅保守進位至元。</p>${input('整筆買進手續費（元）','buyFee')}${input('賣出手續費率（小數）','feeRate')}${input('每次最低手續費（元）','minimumFee')}${input('賣出稅率（小數）','taxRate')}</details><details class="more"${p?' open':''}><summary>成交後管理</summary><p class="meta">到價不代表成交。以下僅更新計畫，實際賣出仍需另外記帳。</p>${input('已確認首次分批成交股數（未成交填 0）','sold')}${input('分批成交後已確認最高價（未知填 0）','high')}<p class="meta">最高價須在分批成交後觀察；系統不會從日收盤推測盤中最高價。追蹤距離固定 2R。</p><label class="radio-line"><input name="closed" type="checkbox"${p?.closed?' checked':''}>結束計畫（清倉後自行勾選）</label></details><p class="error" data-swing-error role="alert" hidden></p><div class="actions"><button class="secondary" type="button" data-swing-preview>試算出場價</button><button class="primary" type="submit">儲存記事本</button></div><div data-swing-result aria-live="polite"></div><p class="warning">本站不連接券商。請在券商核對觸發價、委託價、股數、有效期與成交；保本是估算，跳空或未成交仍可能虧損。</p></form>`;
}
export function mountSwing(container,old,save){
  const form=container.querySelector('[data-swing-editor]'),out=form.querySelector('[data-swing-result]'),error=form.querySelector('[data-swing-error]');
  const read=()=>{const d=Object.fromEntries(new FormData(form)),p={...d,closed:!!d.closed,protectedStop:old?.protectedStop||0};for(const k of ['entry','stop','quantity','trigger','buyFee','feeRate','minimumFee','taxRate','sold','high']){if(d[k]?.trim()==='')throw Error('請完整填寫計畫數字');p[k]=Number(d[k]);}if(old){for(const k of ['entry','stop','quantity','trigger','symbol','entryDate'])p[k]=old[k];if(p.sold<old.sold||p.high<old.high)throw Error('已確認股數與最高價不可調低；如需更正請結束後另建計畫');}if(!/^\d{4,6}$/.test(p.symbol.trim()))throw Error('請填台股代號');p.symbol=p.symbol.trim();if(!p.sold&&p.high)throw Error('尚未分批成交，最高價請填 0');if(p.sold&&p.high&&p.high<p.entry)throw Error('請核對成交後最高價');return p;};
  const preview=()=>{error.hidden=true;const p=read(),r=swingResult(p);out.innerHTML=`<section class="panel"><strong>＋${n(p.trigger)}R：${n(r.target)} 元</strong><p>原始每股 1R：${n(r.distance)} 元 · 建議首次賣 ${n(r.partial)} 股</p>${r.partial?'':'<p class="warning">僅 1 股無法分批；此計畫只供價格參考。</p>'}<p>分批成交後餘股費後保本參考：${n(swingResult({...p,sold:p.sold||r.partial}).breakeven)} 元</p><p>目前階段計畫停損：${n(r.protective)} 元 · 剩餘 ${n(r.remaining)} 股</p><p class="meta">目標／停損向上取台股個股合法跳動價。保本只分攤餘股買進費，不拿已實現獲利抵扣；未含滑價。達標後須先確認分批成交才提高餘股停損。若行情已低於新停損，請核對券商處理方式，不能視為已受保護。</p></section>`;return {...p,protectedStop:p.sold?r.protective:p.protectedStop};};
  const run=fn=>{try{fn();}catch(e){error.textContent=e.message;error.hidden=false;}};
  form.querySelector('[data-swing-preview]').onclick=()=>run(preview);
  form.addEventListener('input',()=>{out.innerHTML='';error.hidden=true;});
  form.addEventListener('submit',e=>{e.preventDefault();run(()=>save(preview()));});
  if(old)run(preview);
}
