import {roundTwd,taxRounding} from './tw-fees.js';
import {tickUp,validateStrategy} from './swing.js';
export const checkStrategy=validateStrategy;
export function quickResult(entry,s,broker,tax,returnPercent=3){
  checkStrategy(s);if(!Number.isFinite(entry)||entry<=0||entry>1e6||!Number.isFinite(returnPercent)||returnPercent<=-100||returnPercent>10000)throw Error('請填有效買進價與試算漲跌幅');
  const stop=(s.stopMode??'percent')==='price'?s.stopPrice:entry*(1-s.riskPercent/100);
  if(!Number.isFinite(stop)||stop<=0||stop>=entry)throw Error('支撐停損價須大於 0 且低於買進價');
  const tw=broker.tw;if(![tw.rate,tw.discount,tw.min,tax].every(Number.isFinite)||tw.rate<0||tw.discount<0||tw.min<0||tax<0||tw.rate*tw.discount>.1||tax>.1)throw Error('請核對券商費率，此試算支援費率與稅率各不超過 10%');
  const fee=g=>roundTwd(Math.max(g*tw.rate*tw.discount,tw.min),tw.round),levy=g=>roundTwd(g*tax,taxRounding(tw));
  const quantity=s.quantity,buyFee=fee(entry*quantity),outlay=entry*quantity+buyFee,target=tickUp(entry+(entry-stop)*s.trigger),partial=Math.floor(quantity*s.sellPercent/100),remaining=quantity-partial;
  const sale=(price,q=quantity)=>{const gross=price*q,sellFee=fee(gross),sellTax=levy(gross),cost=(entry+buyFee/quantity)*q,pnl=gross-sellFee-sellTax-cost;return {price,quantity:q,sellFee,sellTax,net:gross-sellFee-sellTax,pnl,rate:pnl/cost*100};};
  const cost=(entry+buyFee/quantity)*remaining;
  // Search legal ticks from the known lower bound; net is not monotone at rounded charge boundaries.
  let breakeven=tickUp(cost/remaining),steps=0;
  while(sale(breakeven,remaining).pnl < -1e-8){if(++steps>200000)throw Error('費用過高，請核對券商設定與股數');breakeven=tickUp(breakeven+.001);}
  const theoretical=entry*(1+returnPercent/100),orderPrice=tickUp(theoretical);
  return {entry,stop,riskPercent:(entry-stop)/entry*100,distance:entry-stop,target,targetPercent:(target/entry-1)*100,partial,remaining,buyFee,outlay,breakeven,breakevenPercent:(breakeven/entry-1)*100,theoretical,orderPrice,hypothetical:sale(theoretical),order:sale(orderPrice),targetSale:sale(target,partial||quantity),feeRounding:tw.round,taxRounding:taxRounding(tw)};
}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:4}).format(v);
export function quickForm(u){
  const s=u.state.settings.swing?.defaults||{riskPercent:'',trigger:1.5,quantity:1,sellPercent:50},f=u.field;
  return `<form data-swing-quick novalidate><p class="meta">先存常用策略。幅度模式填買進價；支撐價模式另填本次停損價。股數沿用預設，可按本次波段部位修改；不帶入同股票的其他持股。</p><details class="more"${u.state.settings.swing?.defaults?'':' open'}><summary>我的策略參數</summary>${f('停損設定方式','stopMode','text',s.stopMode||'percent',[['percent','停損幅度（%）'],['price','支撐停損價（元）']])}<div data-percent-stop${s.stopMode==='price'?' hidden':''}>${f('初始停損幅度（%）','riskPercent','number',s.riskPercent??'')}</div><div class="row">${f('開始保本門檻（R）','trigger','number',s.trigger)}</div><div class="row">${f('本次波段股數（2 張填 2000）','quantity','number',s.quantity)}${f('達標先賣比例（%，0 表示不分批）','sellPercent','number',s.sellPercent)}</div><p class="meta">原始 1R＝買進價－停損價；保本啟動價＝買進價＋R 倍數 × 原始 1R。支撐停損價每筆另填，不存成跨股票共用價格；請填你決定的停損觸發價，系統不另加支撐緩衝。</p><button class="secondary" type="button" data-save-strategy>儲存為常用策略</button></details>${f('本次費用券商','broker','text',u.defaultBroker(),u.state.brokers.map(b=>[b.id,b.name]))}<div class="row">${f('買進價格','entry','number','')}${f('報酬率試算：股價漲跌幅（%）','returnPercent','number',3)}</div><div data-price-stop${s.stopMode==='price'?'':' hidden'}>${f('本次支撐停損價（元）','stopPrice','number','')}</div><div data-quick-output aria-live="polite"></div><p class="error" data-quick-error role="alert" hidden></p><p class="meta" data-quick-status role="status"></p><details class="more"><summary>儲存單次買進試算（選填；分批成交請用波段管理）</summary>${f('股票代號','symbol','text','')}${f('波段名稱，例如第二筆 2 股','label','text','')}${f('買進日','entryDate','date',new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei'}).format(new Date()))}<p class="meta">同一檔可建立多筆波段，股數與買進價各自計算。這是獨立計畫，不會替帳本分配賣出批次；帳本仍依原 FIFO 計算。要獨立核算長期／波段成果，請用不同帳戶記帳。</p><button class="primary" type="submit">儲存本次波段</button></details><p class="warning">費後數字為依券商設定的預估，未含滑價，非實際成交保證。本站不下單、不盤中監控；請核對智慧單觸發價、委託價及股數。</p></form>`;
}
export function mountQuick(container,u,{saveDefaults,savePlan}){
  const form=container.querySelector('[data-swing-quick]'),out=form.querySelector('[data-quick-output]'),error=form.querySelector('[data-quick-error]'),status=form.querySelector('[data-quick-status]');
  const syncMode=()=>{const isPrice=form.elements.stopMode.value==='price';form.querySelector('[data-percent-stop]').hidden=isPrice;form.querySelector('[data-price-stop]').hidden=!isPrice;};
  const read=()=>{const d=Object.fromEntries(new FormData(form)),s={stopMode:d.stopMode};for(const k of [...(d.stopMode==='percent'?['riskPercent']:[]),'trigger','quantity','sellPercent']){if(d[k].trim()==='')throw Error('請先填好策略參數');s[k]=Number(d[k]);}checkStrategy(s);return {d,s};};
  const calc=()=>{const {d,s}=read(),b=u.state.brokers.find(b=>b.id===d.broker);if(d.entry.trim()===''||d.returnPercent.trim()==='')throw Error('請填買進價格與試算漲跌幅');if(s.stopMode==='price'){if(d.stopPrice.trim()==='')throw Error('請填本次支撐停損價');s.stopPrice=Number(d.stopPrice);}return {d,s,b,r:quickResult(Number(d.entry),s,b,u.state.settings.tax.stock,Number(d.returnPercent))};};
  const preview=()=>{out.innerHTML='';error.hidden=true;const {s,r}=calc();out.innerHTML=`<section class="panel"><h3>上漲 ${n(r.targetPercent)}%（${n(r.target)} 元）開始保本</h3><p>原始 1R＝${n(r.distance)} 元（風險 ${n(r.riskPercent)}%） · ${n(s.trigger)}R · 每股上漲 ${n(r.target-r.entry)} 元 · 原始停損試算 ${n(r.stop)} 元</p><p>${r.partial?`達標先賣 ${n(r.partial)} 股，確認成交後保護剩餘 ${n(r.remaining)} 股`:'本次不分批；達標後將全數部位停損移到保本'}。</p>${s.sellPercent>0&&!r.partial?'<p class="warning">股數不足，分批股數取整後為 0，本次改顯示全數部位保本。</p>':''}<strong>費後保本價 ${n(r.breakeven)} 元（＋${n(r.breakevenPercent)}%）</strong>${r.breakeven>=r.target?'<p class="warning">費後保本價不低於啟動目標，達標時尚不足以設在此價保本；請重新檢查費用、股數或門檻。</p>':''}<hr><h3>報酬率試算</h3><p>理論價格 ${n(r.theoretical)} 元 → 可用委託參考 ${n(r.orderPrice)} 元</p><p>理論價格全數賣出：費後損益 ${n(r.hypothetical.pnl)} 元／費後報酬率 ${n(r.hypothetical.rate)}%</p><p>委託參考價全數賣出：費後損益 ${n(r.order.pnl)} 元／費後報酬率 ${n(r.order.rate)}%</p><p class="meta">以本次 ${n(s.quantity)} 股一次買進、一次全數賣出試算；報酬率分母為含買進費的支出 ${n(r.outlay)} 元。買進費 ${n(r.buyFee)}、參考價賣出費 ${n(r.order.sellFee)}、稅 ${n(r.order.sellTax)} 元。保本價另按餘股股數、分攤買進費與一次賣出費稅計算，不以已獲利部分抵扣。委託參考向上取台股個股跳動價；實際成交價可能不同。</p></section>`;return calc();};
  const run=fn=>{try{return fn();}catch(e){error.textContent=e.message;error.hidden=false;}};
  form.addEventListener('input',()=>{status.textContent='';syncMode();run(preview);});form.addEventListener('change',()=>{syncMode();run(preview);});
  form.querySelector('[data-save-strategy]').onclick=()=>run(()=>{saveDefaults(read().s);error.hidden=true;status.textContent='常用策略已儲存；支撐價模式每筆另填停損價。';});
  form.addEventListener('submit',e=>{e.preventDefault();run(()=>{const {d,s,b,r}=preview();if(!/^\d{4,6}$/.test(d.symbol.trim()))throw Error('儲存記事本需要台股個股代號');savePlan({symbol:d.symbol.trim(),label:d.label.trim(),entryDate:d.entryDate,entry:r.entry,stop:r.stop,stopMode:s.stopMode,quantity:s.quantity,trigger:s.trigger,sellPercent:s.sellPercent,buyFee:r.buyFee,feeRate:b.tw.rate*b.tw.discount,minimumFee:b.tw.min,taxRate:u.state.settings.tax.stock,feeRounding:r.feeRounding,taxRounding:r.taxRounding,sold:0,high:0,protectedStop:0,notes:'',closed:false});});});
}
