import {mkdir,readFile,writeFile,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {checkFx} from '../fx.js';
import {checkCatalog} from '../network.js';
const files=['index.html','ui.css','main.js','updates.js','update.html','update-page.js','update-utils.js','book.js','cash.js','period.js','results.js','network.js','quote-status.js','fx.js','symbols.js','panels.js','offline.js','mark.svg','manifest.json','data/taiwan.json','data/fx.json'];
const root=new URL('../',import.meta.url),out=new URL('../dist/',import.meta.url);
checkCatalog(JSON.parse(await readFile(new URL('data/taiwan.json',root),'utf8')));
for(const f of files.filter(f=>f.endsWith('.js')))execFileSync(process.execPath,['--check',fileURLToPath(new URL(f,root))],{stdio:'inherit'});
const fx=JSON.parse(await readFile(new URL('data/fx.json',root),'utf8'));if(fx.status!=='unavailable')checkFx(fx);
const html=await readFile(new URL('index.html',root),'utf8'),pkg=JSON.parse(await readFile(new URL('package.json',root),'utf8'));
if(!html.includes('慢慢記 '+pkg.version))throw Error('首頁與程式版本不一致');
for(const f of files)await readFile(new URL(f,root));
if(process.argv.includes('--check')){console.log('發布檢查通過：網站檔案、程式語法、行情格式與版本一致。');process.exit(0);}
await mkdir(new URL('data/',out),{recursive:true});
for(const f of files)await copyFile(new URL(f,root),new URL(f,out));
const hash=createHash('sha256');for(const f of files.filter(f=>!f.startsWith('data/')))hash.update(await readFile(new URL(f,root)));
const worker=(await readFile(new URL('offline.js',root),'utf8')).replace(/PREFIX\+'v[0-9]+'/ ,`PREFIX+'${hash.digest('hex').slice(0,16)}'`);
await writeFile(new URL('offline.js',out),worker);
await writeFile(new URL('.nojekyll',out),'');
console.log('完成 dist：純靜態檔案，不含帳本、Token 或任何個人試算表。');
